config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => { :sign_up => 'join' }
  resources :lists
  resources :users
  resources :tasks

  root 'lists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
  validates_presence_of :name
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  has_many :tasks, through: :lists

  validates_presence_of :first_name, :last_name

  # email, password, and password_confirmation are validated by Devise

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  def name
    first_name + " " + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    3.times { @list.tasks.build }

    respond_to do |format|
      format.html { render 'new' }
      format.js   # render lists/new.js.erb
    end

  end

  # GET /lists/1/edit
  def edit

    # respond_to do |format|
    #   format.html { render :edit }
    #   format.js   # render lists/edit.js.erb
    # end

  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.js   # render lists/create.js.erb
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :user_id, tasks_attributes: [:id, :name, :due, :completed])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.list_id = @list.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :due, :completed, :list_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Taskdash &#10004;".html_safe, root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li role="presentation"><%= link_to 'Edit profile', edit_user_registration_path %></li>
        </ul>
      </li>

      <li role="presentation"><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
      <% else %>
      <li role="presentation"><%= link_to "Join", new_user_registration_path, :class => 'navbar-link' %></li>
      <li role="presentation"><%= link_to "Sign in", new_user_session_path, :class => 'navbar-link' %></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/application/_sidebar.html.erb
<aside class="sidebar col-md-3">
  <div id="home">
    <%= link_to "Home", root_path %>
  </div>
  <div id="lists">
    <ul>
      <% current_user.lists.each do |list| %>
      <li><%= link_to list.name, list_path(list.id) %></li>
      <% end %>
    </ul>
  </div>
  <div id="create-list">
    <%= link_to "Create list", new_list_path %>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Taskdash</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'nav' %>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_edit.html.erb
<%= form_for(@list, remote: true) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "hidden" %>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>

  <%= f.fields_for :tasks do |task| %>
    <li>
      <%= task.label :name, class: "hidden" %>       <%= task.text_field :name %>
      <%= task.label :due %>        <%= task.datetime_select :due, ampm: true %>
      <%= task.label :completed %>  <%= task.check_box :completed %>
    </li>
  <% end %>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_for(@list, html: { class: "form-horizontal" }) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name, class: "hidden" %>
      <%= f.text_field :name, class: "form-control", placeholder: "List name" %>
    </div>
  </div>

  <%= f.fields_for :tasks do |task| %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= task.label :name, class: "hidden" %>
      <%= task.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-5">
      <%= task.label :due %>
      <%= task.datetime_select :due, ampm: true, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= task.label :completed %>
      <%= task.check_box :completed, class: "checkbox" %>
    </div>
  </div>
  <% end %>

  <div class="actions form-group">
    <% if @list.new_record? %>
      <%= f.submit "Create list", class: "btn btn-default" %>
    <% else %>
      <%= f.submit "Save changes", class: "btn btn-default" %>
      <%= link_to "Delete list", list_path, class: "btn btn-warning", data: { confirm: "Are you sure you want to delete \"#{@list.name}\"?" }, method: :delete %>
    <% end %>
  </div>

<% end %>

app/views/lists/_list.html.erb
<article class="col-sm-3 list-container">
  <h1><%= list.name %></h1>
  <ul>
    <% list.tasks.each do |task| %>
    <li><%= task.name %>
      <% if !task.due.nil? %>
      <ul>
        <li>
          <small>due <%= task.due %></small>
        </li>        
      </ul>
      <% end %>
    </li>
    <% end %>
  </ul>
  <%= link_to 'Edit', edit_list_path(list) %>
</article>

app/views/lists/_new.html.erb
<article class="col-sm-3 list-container" id="new-list-container">
  <%= form_for(@list, remote: true, html: { class: "form-horizontal"}) do |f| %>
  <% if @list.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

    <ul>
      <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "hidden" %>
    <%= f.text_field :name, class: "form-control", placeholder: "List name" %>
  </div>

  <div class="form-group">
    <ul>
      <%= f.fields_for :tasks do |task| %>
      <li>
        <%= task.label :name, class: "hidden" %>  <%= task.text_field :name, class: "form-control", placeholder: "Task" %>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="form-group">
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
  </div>
  <% end %>
</article>

app/views/lists/_show.html.erb
<article class="col-sm-3 list-container">
  <h1><%= @list.name %></h1>
  <ul>
    <% @list.tasks.each do |task| %>
    <li><%= task.name %>
      <% if !task.due.nil? %>
      <small>due <%= task.due %></small>
      <% end %>
    </li>
    <% end %>
  </ul>
  <%= link_to 'Edit', edit_list_path(@list) %>
</article>

app/views/lists/create.js.erb
$("#new-list-container").replaceWith("<%= j render :partial => 'show' %>");

// $(".container").html("<%= j render 'show' %>");
// window.location.replace("<%= request.base_url %>/lists/<%= @list.id %>");

app/views/lists/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<%= render current_user.lists %>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/new.js.erb
$("#new-list-link-container").replaceWith('<%= j render :partial => "new" %>');

app/views/lists/show.html.erb
<h1>
  <%= @list.name %>
</h1>

<ul>
  <% @list.tasks.each do |task| %>
  <% if task.completed %>
  <s>
    <% end %>
    <li><%= task.name %></li>
    <small>due <%= task.due %></small>
    <% if task.completed %>
  </s>
  <% end %>
  <% end %>  
</ul>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.datetime_select :due %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Due</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.due %></td>
        <td><%= task.completed %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>